config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :house_images
  resources :sections, only: [:new, :create]
  resources :users, only: [:index, :show]


  root 'house_images#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/house_image.rb
class HouseImage < ApplicationRecord
  belongs_to :section
end

app/controllers/house_images_controller.rb
class HouseImagesController < ApplicationController
  before_action :set_house_image, only: [:show, :edit, :update, :destroy]

  # GET /house_images
  # GET /house_images.json
  def index
    @house_images = HouseImage.all
  end

  # GET /house_images/1
  # GET /house_images/1.json
  def show
  end

  # GET /house_images/new
  def new
    @house_image = HouseImage.new
  end

  # GET /house_images/1/edit
  def edit
  end

  # POST /house_images
  # POST /house_images.json
  def create
    @house_image = HouseImage.new(house_image_params)

    respond_to do |format|
      if @house_image.save
        format.html { redirect_to @house_image, notice: 'House image was successfully created.' }
        format.json { render :show, status: :created, location: @house_image }
      else
        format.html { render :new }
        format.json { render json: @house_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /house_images/1
  # PATCH/PUT /house_images/1.json
  def update
    respond_to do |format|
      if @house_image.update(house_image_params)
        format.html { redirect_to @house_image, notice: 'House image was successfully updated.' }
        format.json { render :show, status: :ok, location: @house_image }
      else
        format.html { render :edit }
        format.json { render json: @house_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /house_images/1
  # DELETE /house_images/1.json
  def destroy
    @house_image.destroy
    respond_to do |format|
      format.html { redirect_to house_images_url, notice: 'House image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house_image
      @house_image = HouseImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_image_params
      params.require(:house_image).permit(:url, :tags, :section, :score)
    end
end

app/helpers/house_images_helper.rb
module HouseImagesHelper
end

app/views/house_images/_form.html.erb
<%= form_for HouseImage.new do |form| %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :house_image_url %>
  </div>

  <div class="field">
    <%= form.label :section %>
    <%= form.select :section, [['exteriors'], ['grounds'], ['gardens'], ['external buildings'], ['living rooms'], ['kitchens'], ['bedrooms'], ['bathrooms'], ['basements'], ['storage'], ['decor']], id: :house_image_section %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags, id: :house_image_tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/house_images/edit.html.erb
<h1>Editing House Image</h1>

<%= render 'form', house_image: @house_image %>

<%= link_to 'Show', @house_image %> |
<%= link_to 'Back', house_images_path %>

app/views/house_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Our House</h1>


  <%= render 'form' %>
  <div class="row">
    <% @house_images.each do |house_image| %>
        <div class="col-md4">
          <div class="card">
            <img class="card-img-top img-responsive" src="<%= house_image.url%>" alt="<%= house_image.url%>">
            <div class="card-block">

              <p class="card-text"><%= house_image.tags %></p>
              <p class="card-text"><%= house_image.score %></p>
              <%= link_to 'Show', house_image %>
              <%= link_to 'Edit', edit_house_image_path(house_image) %>
              <%= link_to 'Destroy', house_image, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>

    <% end %>
  </div>



<br>

app/views/house_images/new.html.erb
<h1>New House Image</h1>

<%= render 'form', house_image: @house_image %>

<%= link_to 'Back', house_images_path %>

app/views/house_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @house_image.url %>
</p>

<p>
  <strong>Section:</strong>
  <%= @house_image.section %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @house_image.tags %>
</p>

<p>
  <strong>Score:</strong>
  <%= @house_image.score %>
</p>

<%= link_to 'Edit', edit_house_image_path(@house_image) %> |
<%= link_to 'Back', house_images_path %>